name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read

jobs:
  test-github:
    name: MadCheck - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        julia-version: ['1']
        julia-arch: [x64]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/install-juliaup@v2
        with:
          channel: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
